# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do aluno')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='turma do aluno 4')),
                ('age', models.CharField(blank=True, choices=[('1', 'Menos de 5'), ('2', 'De 5 a 8 anos'), ('3', 'De 9 a 12 anos'), ('4', 'De 12 a 15 anos'), ('5', 'De 16 a 18 anos'), ('6', 'Acima de 18 anos')], max_length=100, verbose_name='idade do aluno 4')),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='envolved',
            new_name='involved',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='envolved_description',
            new_name='involved_description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='aluno1',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='aluno2',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='aluno3',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='aluno4',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='idade1',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='idade2',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='idade3',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='idade4',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='turma1',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='turma2',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='turma3',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='turma4',
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.ManyToManyField(to='core.Student'),
        ),
    ]
